- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable old and enable latest nodejs
      ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop
    
    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download file
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: unzip file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app/
        remote_src: yes

    - name: install npm
      ansible.builtin.command: npm install
      args:
        chdir: /app
    
    - name: copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/

    - name: daemon reload
      ansible.builtin.systemd_service:
        name: catalogue
        daemon_reload: true

    - name: copy mongo-db repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/

    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present

    - name: get the categories count
      ansible.builtin.command:  mongo --host mongodb.mohankodela.shop --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{product_count}}"

    - name: load catalogue data
      ansible.builtin.command: mongo --host mongodb.mohankodela.shop < /app/schema/catalogue.js
      when: product_count.stdout == "0" # keep double quotes

    - name: start and enable catalogue
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes        

