- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable old and enable latest nodejs
      ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop
    
    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download file
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: unzip file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app/
