- name: shipping
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:
    - name: install maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: Ensure python3-pip is installed
      ansible.builtin.command: yum install python39-pip -y

    - name: install PyMySQL and cryptography 
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - cryptography
        - PyMySQL
        - mysqlclient
        - MySQL-python
    
    - name: add roboshop user
      ansible.builtin.user:
        name: roboshop
    
    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent
    
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: Download package
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: unzip package to app directory
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
    
    - name: istall package dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app
    
    - name: rename the file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app
    
    - name: copy the service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/

    - name: daemon_reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: install mysql
      ansible.builtin.package:
        name: mysql
        state: present

    - name: import data
      tags:
      - import
      community.mysql.mysql_db:
          name: all
          login_user: root
          login_password: RoboShop@1
          login_host: mysql.mohankodela.shop
          state: import
          target: "{{ item }}"
      loop:
        - /app/db/schema.sql
        - /app/db/app-user.sql
        - /app/db/master-data.sql


    - name: start and enable shipping
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: yes